name: tasks-build-action
on: [push]
jobs:
  run-tasks-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14', '16']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    name: Build with Node ${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2           # checks out of repository and download it to the runner
      - uses: actions/setup-node@v2         # installing node
        with:
          node-version: ${{ matrix.node }}  # Node version
      - run: npm run build
      - uses: codecov/codecov-action@v1     # publishing code coverage results
        with:
          files: coverage/cobertura-coverage.xml
          name: codecov for Node ${{ matrix.node }} on ${{ matrix.os }}
